/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueryRouteImport } from './routes/query'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TableNameRouteImport } from './routes/table.$name'
import { Route as DatasetIdRouteImport } from './routes/dataset.$id'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRunsRouteImport } from './routes/admin.runs'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDataIndexRouteImport } from './routes/admin.data.index'
import { Route as AdminDataIdRouteImport } from './routes/admin.data.$id'

const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TableNameRoute = TableNameRouteImport.update({
  id: '/table/$name',
  path: '/table/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetIdRoute = DatasetIdRouteImport.update({
  id: '/dataset/$id',
  path: '/dataset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRunsRoute = AdminRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataIndexRoute = AdminDataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataIdRoute = AdminDataIdRouteImport.update({
  id: '/data/$id',
  path: '/data/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/datasets': typeof DatasetsRoute
  '/query': typeof QueryRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/dataset/$id': typeof DatasetIdRoute
  '/table/$name': typeof TableNameRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/data/$id': typeof AdminDataIdRoute
  '/admin/data/': typeof AdminDataIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/datasets': typeof DatasetsRoute
  '/query': typeof QueryRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/dataset/$id': typeof DatasetIdRoute
  '/table/$name': typeof TableNameRoute
  '/admin': typeof AdminIndexRoute
  '/admin/data/$id': typeof AdminDataIdRoute
  '/admin/data': typeof AdminDataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/datasets': typeof DatasetsRoute
  '/query': typeof QueryRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/dataset/$id': typeof DatasetIdRoute
  '/table/$name': typeof TableNameRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/data/$id': typeof AdminDataIdRoute
  '/admin/data/': typeof AdminDataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/contact'
    | '/datasets'
    | '/query'
    | '/admin/audit'
    | '/admin/runs'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/storage'
    | '/admin/users'
    | '/api/$'
    | '/dataset/$id'
    | '/table/$name'
    | '/admin/'
    | '/admin/data/$id'
    | '/admin/data/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/contact'
    | '/datasets'
    | '/query'
    | '/admin/audit'
    | '/admin/runs'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/storage'
    | '/admin/users'
    | '/api/$'
    | '/dataset/$id'
    | '/table/$name'
    | '/admin'
    | '/admin/data/$id'
    | '/admin/data'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/contact'
    | '/datasets'
    | '/query'
    | '/admin/audit'
    | '/admin/runs'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/storage'
    | '/admin/users'
    | '/api/$'
    | '/dataset/$id'
    | '/table/$name'
    | '/admin/'
    | '/admin/data/$id'
    | '/admin/data/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskRoute: typeof AskRoute
  ContactRoute: typeof ContactRoute
  DatasetsRoute: typeof DatasetsRoute
  QueryRoute: typeof QueryRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DatasetIdRoute: typeof DatasetIdRoute
  TableNameRoute: typeof TableNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/table/$name': {
      id: '/table/$name'
      path: '/table/$name'
      fullPath: '/table/$name'
      preLoaderRoute: typeof TableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset/$id': {
      id: '/dataset/$id'
      path: '/dataset/$id'
      fullPath: '/dataset/$id'
      preLoaderRoute: typeof DatasetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/runs': {
      id: '/admin/runs'
      path: '/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminRunsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/': {
      id: '/admin/data/'
      path: '/data'
      fullPath: '/admin/data/'
      preLoaderRoute: typeof AdminDataIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/$id': {
      id: '/admin/data/$id'
      path: '/data/$id'
      fullPath: '/admin/data/$id'
      preLoaderRoute: typeof AdminDataIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminRunsRoute: typeof AdminRunsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDataIdRoute: typeof AdminDataIdRoute
  AdminDataIndexRoute: typeof AdminDataIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminRunsRoute: AdminRunsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDataIdRoute: AdminDataIdRoute,
  AdminDataIndexRoute: AdminDataIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AskRoute: AskRoute,
  ContactRoute: ContactRoute,
  DatasetsRoute: DatasetsRoute,
  QueryRoute: QueryRoute,
  ApiSplatRoute: ApiSplatRoute,
  DatasetIdRoute: DatasetIdRoute,
  TableNameRoute: TableNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
